version: "3"
services:
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'service-web'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  fastapi:
    build:
      context: .
    container_name: fastapi_api_project
    volumes:
      - ./src:/app/code
    ports:
     - 5000:80
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: